# prod-edge-london — RAN MEC site, SR-IOV NICs, 3 replicas across NUMA
replicaCount: 3

resources:
  requests:
    cpu: 2000m
    memory: 2Gi
  limits:
    cpu: 4000m
    memory: 4Gi

nodeSelector:
  node-role.telco/edge: "true"
  topology.kubernetes.io/zone: "uk-london-edge-1"

tolerations:
  - key: edge
    operator: Exists
    effect: NoSchedule

multus:
  enabled: true
  networks:
    - name: n3-sriov
      type: sriov
      vlan: 200
      ipam:
        type: whereabouts
        range: 10.200.10.0/24
    - name: n6-sriov
      type: sriov
      vlan: 600
      ipam:
        type: whereabouts
        range: 10.60.10.0/24
