apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-upf.fullname" . }}
  labels:
    {{- include "demo-upf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $port := .Values.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      protocol: {{ $port.protocol }}
      targetPort: {{ $port.name }}
    {{- end }}
  selector:
    {{- include "demo-upf.selectorLabels" . | nindent 4 }}
